worlds:
  - world
title_messages:
  5:
    - "%1$s is doin mega killin (main title)"
    - "That means 5 whole kills! (subtitle)"
  10:
    - "$1$s is killbominable"
    - "(10 kil!)"
chat_messages:
  3: "%1$s is on 3 killstreak! wowie!"
commands:
  5:
    - "tell %1$s good job!"