name: Killstreaks
version: ${project.version}
main: henry232323.killstreaks.Killstreaks
authors: [henry232323]
description: A plugin for tracking killstreaks
website: http://github.com/henry232323/Killstreaks
